var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                     xxxxx        ",
   "                                                   #                      x     ",
   "                                                                           x    ",
   "                                                              o            x    ",
   "                                                              ^            x    ",
   "                                   x               xx   xx   xxx           x    ",
   "                                   x o o      xx   v    v     v            x    ",
   "                                   x  ^                                     x   ",
   "       #                          vxxxxxx                                   x   ",
   "                                           x           #                    xx  ",
   "  xx                                      o o  x                             x  ",
   "  x            ^                           o                       #         x  ",
   "  x           xxx                        xxxxx                             o x  ",
   "  x          x  x       o             x  x   x                               x  ",
   "  x  @  ^^  x   x          ^^    x   ^^^ x   xx ^^^^    x    $             ^ x  ",
   "  xxxxxxxxxxx   xxx      xxxxxx     xxxxxx   xxxxxxxxx     xxxxx          xxxx  ",
   "                   x ^^ x      x   x                 x     x   x          x     ",
   "                    xxxx       x!!!x                 x!!!!!x    x       xx      ",
   "                               x!!!x                 x!!!!!x    x!!!!!xx        ",
   "                               xxxxx                 xxxxxxx    x!!!!x          ",
   "                                                                 xxxx           ",
   "                                                                                "],
	
	
	
	
  [" xxxxxxxxxx                                                    ^^^xxxxxxx^^^                   ^xxxxxxxxxxxx^     ",
   " x        x                                                   ^xxxx     xxxx^   xxx  xx  xxx  ^xx          xx^    ",
   " x^^    @ x                                                  ^xx     #    xx^xxxxxxxxxxxxxxxxxx             xx ^  ",
   "  xx    xx             #                                     xx             xxx                       o      x!x  ",
   "  ^x $  x^                                                    x                                   o       o ^x!x  ",
   "  x^    ^x                #                       ^^^^^^^^^^^x     o   o                              ^     xx!x  ",
   "  xx    xx                                       ^^xxxxxxxxxxxx                                xxxxx  x  xxxx!!x  ",
   "  v     v                                      ^xx                 x   x                   o o x!!!!!!!!!!!!!!xx  ",
   "                                               x  #              |   |   |  xx       xx   xxxxxxxxxxxxxxxxxxxxx   ",
   "                            #                  x         ^^   xx!!!!!!!!!!!xx            v    x                   ",
   "                                               x      xxxxxxxxxxxxx!!!!!xxxx     x            x                   ",
   "                 #              #               x     x           xxxxxxx                     x                   ",
   "                                                x    xx                            xx         x                   ",
   "                                               ^x     x             #    #          x         x                   ",
   "                                               x     x                             xx        xx       o o         ",
   "                                                xx    x                             x    x   x        xxx         ",
   "                  ^              #             ^x     x     o  o                    x    v   x      #   #         ",
   "           ^^^ xxxxxxx                        ^x     x       ^^                   x^         x    xx              ",
   "         xxxxxxx v v xx                       x     x      xxxxxx   xx   x   xxxxxxxxx       x                    ",
   "        x  v  v      xx                       x    xx      x!!!!x    x   x!!!!x              x   x                ",
   "       x              x                       x     x      xxxxxx    x   x!!!x               x                    ",
   "  xx^ x                        ^x o x^         x     x               x   xxxxx    xx           x                  ",
   "    x!x                        xx o xx         x     x               xx    o     x  x           x                 ",
   "!!!!x!x!!!!!!x^^^^^^^^xx!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!^    x^    =   ^^x  x   o o    x                  ",
   "!!!!x!x!!!!!!xxxxxxxxxxx!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!x    xxxxxxxxxxxxx  xx       xx                   ",
   "!!!!x!x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !^                    xx^^^^^xx                    ",
   "!!!!x!x!!!!!!x         x!!!!!x                    ^xx!!!!!!xx  !x                     xxxxxxx                     ",
   "!!!!x!x!!!!!!x         x!!!!!xx  ^^^      xxxx xxxxxx!!!!!!xx  !^                                                 ",
   "!!!!x!x!!!!!!x         x!!!!!!xxxxxxxxxxxx!!!!!!!!!!!!!!!xx    !x                                                 ",
   "!!!!x!x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                       ^^^^^^^                                                                                ",
   "                       xxxxxxx^^        #                                                                     ",
   "                     ^^xx     xx                                      #                                       ",
   "                    ^xx   #   xx^                                                         #                   ",
   "                  ^^xx         xx    xxx                         ^                                            ",
   "                 ^xxx         ox   xx   xx                       x          x    ^                            ",
   "                ^xx     o     xx xx      x                      !!!        !!!  xxx                           ",
   "                xx o    x    xxxx        x                      !x!   oo   !x!          x                     ",
   "              ^^xxxx                    xxx xxx                 x!    oo    x                                 ",
   "              xx                         x^  x ^                x!    oo    x           xxx                   ",
   "               xx    x   x!!!x            x    x                x!    xx    x          x!!!x                  ",
   "               x    x    xxxxx        ^    xx   x                xx!!!!!!!!!x       x   xxx                   ",
   "               x o                   xxxxxxxx    ^    x           xxx!!!!!xxx                                 ",
   "               xxx               x    x   xxxx  xxx   xx             xxxxx      x xx                          ",
   "               x^^o                   x   x  x!!x     x      x                  x!!!x                         ",
   "               xxxx                  x   x   xxxx    x                      x    xxx                          ",
   "                xx           x==   xx   xx          x      x       ^                    #                     ",
   "                  xx                 x   x= = = =    x            xxx                                         ",
   "                   xx  ^              x   x           x           x!!!x      $ o                              ",
   "                    xxxxxx             x   x    = = = =x     o      xxx     ^xxx                              ",
   "                         xx          xx   xx         xx                     x!!!x   x    o                    ",
   "                          xx  o       x!!!x          xx     x                xxv       ^xxx      o            ",
   "                            xx        x!!!x^^        xx              x                 x!!!x          #       ",
   "                            xxxxxx   xxxxxxxxx   o o xx!!!!!!!!!!!!!!x                   vx      ^            ",
   "                            x xx             x    ^  xx!!!!!!!!!!!!!!x                         ^xxx           ",
   "                            x xx          ^ x    xxxxxxxxxxxxxxxxxxxxxx         o              x!!!x          ",
   "  ^^^                        xxxxx        xx     x^xx^xx^xx^xx^xx^xx^xx        xxx              xvx       o^  ",
   "  xxx                         x     x     x                                   x!!!x      x               xxx  ",
   "  x x                         x    xxx    x ^^^^         $                     xxx                     xxx x  ",
   "  x      #              #     x   xxxx    xxxxxxx      xxxxx             ^                    xx    x      x  ",
   "  x^                          x                      xxx   xxx          xxx                  x!!x          x  ",
   "  xx                          xx                    x    ^    x        x x x                xx!!x          x  ",
   "  x                 ^                            x   xxxxxxxxx       xx  o  xx              ^^xx           x  ",
   "  x^               xxx             o o     $^                                            xxxxx             x  ",
   "  xx              xxxxx       xx    ^     xxxx                          xxx     x!!!x^^^x                  x  ",
   "  x                xxx        x    xxx    x  x                          x x^  xxxxxxxxxxx                  x  ",
   "  x             ^xxxxxxx^     x   x   x   x  x o  x      oo     x oo  xx  xxxx                             x  ",
   "  x^^^^^ @      xxxxxxxxx^^^^^x!!!!!!!!!!!x!!x  ^ x!!!!x ^  x!!!!x ^  xx    xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["        xxxxxxxxxxx    xxxxxxxxx                                xxxxxxx^^^^^^^^xxxxxxx^^^^^^^^xxxxxxx x       ",
   "      xxx          x  x                        ^           o xxx!!!!!!!xxxxxxxx!!!!!!!xxxxxxxx!!!!!!! x       ",
   "    xxx     o       xx                xx!!!!!xxxxx!!!!!!!xxxx   xxxxxxx        xxxxxxx        xxxxxxxxx       ",
   "  xxx     xxxxx          o        x   xx!!!!x     xx!!!!xxxx                                      x           ",
   "  x      x     xx           xx        xx!!!x        xxxx              #           #               x xxx       ",
   "  x     x             o               xx!!x                                                       x x x       ",
   "  x #  x   o   x   x                   xxxx     #      #        o     o     o     o          o o oxxx x       ",
   "  x    x      x      xxx                                                                           ^^^x       ",
   "  x   ^!  o  !                  #                           $ x   x x   x x   x x   x x   x xxxxx xxxxx       ",
   "  x   x     x^                                              x x!!!x x!!!x x!!!x x!!!x x!!!x x!!!x x           ",
   "  x    x  o  x^           x                                   xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "  x     x     x                            #            x       x x!!!x x!!!x x!!!x x!!!x x!!!x x!!!!!x       ",
   "  x    !  o  !^           o    x                             xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "  x    ^x    ^x                            o                               oo       #     x oo  xx    x       ",
   "  x    x   o x           x x                                xx                            x     x     x       ",
   "  x     x     x        xx!!!xx            xxx                      xxxx       x   xxxxx   xxx   xxxxxxx       ",
   "  x   ^!  o  !        xx!!!!!xx     x      x     x                      x o           xx   xx  xx^^^^^^       ",
   "  x   x     x^        x!!!!!!!x     v                 xx                        o      xx o x   xxxxxxx^      ",
   "  x    x o   x     xxxxxxxxxxxxxxx                    v                  xxx             xxxxx  x x    x      ",
   "  x  ^!    ^!                                                     xx      x    xxx      $       x xxxx x      ",
   "  x  x  o  x              o                                                     x      xxxxxxxxxxxxxxxxx^     ",
   "  x                                                       xx     xx                         ^   x o x   x     ",
   "  x #                    xxx     xxx    #                                x                  x   x   x^^^x     ",
   "  x              xx                              #                                             x   xxxxx      ",
   "  x                                                           ||                     #    #     x    xx       ",
   "  xxxx    xxx    ^    ^        ^$^                                                                 xx^^       ",
   "  x  x!!!!xvx o xxxx xxxx o xxxxxxxxx o xx                                                          ^xx       ",
   "  x  xxxxxx x!!!x  x!x                                  ||          ||          x             ^xxxxxx         ",
   "  x  @      xxxxx  xxx          o               ^                        $                ^xxxxx              ",
   "  xxxxxxx           o                         xxxxx        xx     xx    xxx             xxxxx                 ",
   "        x    ^^          ^^ =         ^$^    =x   x            x        xxx      x                            ",
   "        xxxxxxxxxx!!!!!xxxxxxxx!!!xxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                 xxxxxxx      xxxxx               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
